"""
Central configuration for all 18 Gen 1-5 games.
Each entry defines scraping slugs, PokeAPI slugs, starters, and known
checkpoint names (used for heading classification in the scraper).
"""

GAMES = {
    # ── Gen 1 ──────────────────────────────────────────────────────────────────
    "red": {
        "id": "red",
        "name": "Pokémon Red",
        "gen": 1,
        "region": "kanto",
        "starters": ["Bulbasaur", "Charmander", "Squirtle"],
        "walkthrough_slug": "Red_and_Blue_walkthrough",
        "shared_with": "blue",          # shared walkthrough partner
        "pokeapi_version": "red",
        "pokeapi_region": "kanto",
        "gym_leaders": ["Brock", "Misty", "Lt. Surge", "Erika", "Koga", "Sabrina", "Blaine", "Giovanni"],
        "rivals": ["Blue", "Rival"],
        "elite4": ["Lorelei", "Bruno", "Agatha", "Lance"],
        "champion": ["Blue"],
        "bosses": ["Giovanni"],         # named non-gym boss fights
    },
    "blue": {
        "id": "blue",
        "name": "Pokémon Blue",
        "gen": 1,
        "region": "kanto",
        "starters": ["Bulbasaur", "Charmander", "Squirtle"],
        "walkthrough_slug": "Red_and_Blue_walkthrough",
        "shared_with": "red",
        "pokeapi_version": "blue",
        "pokeapi_region": "kanto",
        "gym_leaders": ["Brock", "Misty", "Lt. Surge", "Erika", "Koga", "Sabrina", "Blaine", "Giovanni"],
        "rivals": ["Blue", "Rival"],
        "elite4": ["Lorelei", "Bruno", "Agatha", "Lance"],
        "champion": ["Blue"],
        "bosses": ["Giovanni"],
    },
    "yellow": {
        "id": "yellow",
        "name": "Pokémon Yellow",
        "gen": 1,
        "region": "kanto",
        "starters": ["Pikachu"],
        "walkthrough_slug": "Yellow_walkthrough",
        "shared_with": None,
        "pokeapi_version": "yellow",
        "pokeapi_region": "kanto",
        "gym_leaders": ["Brock", "Misty", "Lt. Surge", "Erika", "Koga", "Sabrina", "Blaine", "Giovanni"],
        "rivals": ["Blue", "Rival"],
        "elite4": ["Lorelei", "Bruno", "Agatha", "Lance"],
        "champion": ["Blue"],
        "bosses": ["Giovanni"],
    },

    # ── Gen 2 ──────────────────────────────────────────────────────────────────
    "gold": {
        "id": "gold",
        "name": "Pokémon Gold",
        "gen": 2,
        "region": "johto",
        "starters": ["Chikorita", "Cyndaquil", "Totodile"],
        "walkthrough_slug": "Gold_and_Silver_walkthrough",
        "shared_with": "silver",
        "pokeapi_version": "gold",
        "pokeapi_region": "johto",
        # Johto gyms then Kanto gyms
        "gym_leaders": [
            "Falkner", "Bugsy", "Whitney", "Morty", "Chuck", "Jasmine", "Pryce", "Clair",
            "Brock", "Misty", "Lt. Surge", "Erika", "Janine", "Sabrina", "Blaine", "Blue",
        ],
        "rivals": ["Silver"],
        "elite4": ["Will", "Koga", "Bruno", "Karen"],
        "champion": ["Lance"],
        "bosses": ["Giovanni"],
    },
    "silver": {
        "id": "silver",
        "name": "Pokémon Silver",
        "gen": 2,
        "region": "johto",
        "starters": ["Chikorita", "Cyndaquil", "Totodile"],
        "walkthrough_slug": "Gold_and_Silver_walkthrough",
        "shared_with": "gold",
        "pokeapi_version": "silver",
        "pokeapi_region": "johto",
        "gym_leaders": [
            "Falkner", "Bugsy", "Whitney", "Morty", "Chuck", "Jasmine", "Pryce", "Clair",
            "Brock", "Misty", "Lt. Surge", "Erika", "Janine", "Sabrina", "Blaine", "Blue",
        ],
        "rivals": ["Silver"],
        "elite4": ["Will", "Koga", "Bruno", "Karen"],
        "champion": ["Lance"],
        "bosses": ["Giovanni"],
    },
    "crystal": {
        "id": "crystal",
        "name": "Pokémon Crystal",
        "gen": 2,
        "region": "johto",
        "starters": ["Chikorita", "Cyndaquil", "Totodile"],
        "walkthrough_slug": "Crystal_walkthrough",
        "shared_with": None,
        "pokeapi_version": "crystal",
        "pokeapi_region": "johto",
        "gym_leaders": [
            "Falkner", "Bugsy", "Whitney", "Morty", "Chuck", "Jasmine", "Pryce", "Clair",
            "Brock", "Misty", "Lt. Surge", "Erika", "Janine", "Sabrina", "Blaine", "Blue",
        ],
        "rivals": ["Silver"],
        "elite4": ["Will", "Koga", "Bruno", "Karen"],
        "champion": ["Lance"],
        "bosses": ["Giovanni"],
    },

    # ── Gen 3 ──────────────────────────────────────────────────────────────────
    "ruby": {
        "id": "ruby",
        "name": "Pokémon Ruby",
        "gen": 3,
        "region": "hoenn",
        "starters": ["Treecko", "Torchic", "Mudkip"],
        "walkthrough_slug": "Ruby_and_Sapphire_walkthrough",
        "shared_with": "sapphire",
        "pokeapi_version": "ruby",
        "pokeapi_region": "hoenn",
        "gym_leaders": ["Roxanne", "Brawly", "Wattson", "Flannery", "Norman", "Winona", "Tate", "Liza", "Wallace"],
        "rivals": ["May", "Brendan", "Wally"],
        "elite4": ["Sidney", "Phoebe", "Glacia", "Drake"],
        "champion": ["Wallace", "Steven"],
        "bosses": ["Maxie", "Archie", "Tabitha", "Matt"],
    },
    "sapphire": {
        "id": "sapphire",
        "name": "Pokémon Sapphire",
        "gen": 3,
        "region": "hoenn",
        "starters": ["Treecko", "Torchic", "Mudkip"],
        "walkthrough_slug": "Ruby_and_Sapphire_walkthrough",
        "shared_with": "ruby",
        "pokeapi_version": "sapphire",
        "pokeapi_region": "hoenn",
        "gym_leaders": ["Roxanne", "Brawly", "Wattson", "Flannery", "Norman", "Winona", "Tate", "Liza", "Wallace"],
        "rivals": ["May", "Brendan", "Wally"],
        "elite4": ["Sidney", "Phoebe", "Glacia", "Drake"],
        "champion": ["Wallace", "Steven"],
        "bosses": ["Maxie", "Archie", "Tabitha", "Matt"],
    },
    "emerald": {
        "id": "emerald",
        "name": "Pokémon Emerald",
        "gen": 3,
        "region": "hoenn",
        "starters": ["Treecko", "Torchic", "Mudkip"],
        "walkthrough_slug": "Emerald_walkthrough",
        "shared_with": None,
        "pokeapi_version": "emerald",
        "pokeapi_region": "hoenn",
        "gym_leaders": ["Roxanne", "Brawly", "Wattson", "Flannery", "Norman", "Winona", "Tate", "Liza", "Juan"],
        "rivals": ["May", "Brendan", "Wally"],
        "elite4": ["Sidney", "Phoebe", "Glacia", "Drake"],
        "champion": ["Wallace"],
        "bosses": ["Maxie", "Archie"],
    },
    "firered": {
        "id": "firered",
        "name": "Pokémon FireRed",
        "gen": 3,
        "region": "kanto",
        "starters": ["Bulbasaur", "Charmander", "Squirtle"],
        "walkthrough_slug": "FireRed_and_LeafGreen_walkthrough",
        "shared_with": "leafgreen",
        "pokeapi_version": "firered",
        "pokeapi_region": "kanto",
        "gym_leaders": ["Brock", "Misty", "Lt. Surge", "Erika", "Koga", "Sabrina", "Blaine", "Giovanni"],
        "rivals": ["Blue", "Rival"],
        "elite4": ["Lorelei", "Bruno", "Agatha", "Lance"],
        "champion": ["Blue"],
        "bosses": ["Giovanni"],
    },
    "leafgreen": {
        "id": "leafgreen",
        "name": "Pokémon LeafGreen",
        "gen": 3,
        "region": "kanto",
        "starters": ["Bulbasaur", "Charmander", "Squirtle"],
        "walkthrough_slug": "FireRed_and_LeafGreen_walkthrough",
        "shared_with": "firered",
        "pokeapi_version": "leafgreen",
        "pokeapi_region": "kanto",
        "gym_leaders": ["Brock", "Misty", "Lt. Surge", "Erika", "Koga", "Sabrina", "Blaine", "Giovanni"],
        "rivals": ["Blue", "Rival"],
        "elite4": ["Lorelei", "Bruno", "Agatha", "Lance"],
        "champion": ["Blue"],
        "bosses": ["Giovanni"],
    },

    # ── Gen 4 ──────────────────────────────────────────────────────────────────
    "diamond": {
        "id": "diamond",
        "name": "Pokémon Diamond",
        "gen": 4,
        "region": "sinnoh",
        "starters": ["Turtwig", "Chimchar", "Piplup"],
        "walkthrough_slug": "Diamond_and_Pearl_walkthrough",
        "shared_with": "pearl",
        "pokeapi_version": "diamond",
        "pokeapi_region": "sinnoh",
        "gym_leaders": ["Roark", "Gardenia", "Maylene", "Crasher Wake", "Fantina", "Byron", "Candice", "Volkner"],
        "rivals": ["Barry"],
        "elite4": ["Aaron", "Bertha", "Flint", "Lucian"],
        "champion": ["Cynthia"],
        "bosses": ["Cyrus", "Mars", "Jupiter", "Saturn"],
    },
    "pearl": {
        "id": "pearl",
        "name": "Pokémon Pearl",
        "gen": 4,
        "region": "sinnoh",
        "starters": ["Turtwig", "Chimchar", "Piplup"],
        "walkthrough_slug": "Diamond_and_Pearl_walkthrough",
        "shared_with": "diamond",
        "pokeapi_version": "pearl",
        "pokeapi_region": "sinnoh",
        "gym_leaders": ["Roark", "Gardenia", "Maylene", "Crasher Wake", "Fantina", "Byron", "Candice", "Volkner"],
        "rivals": ["Barry"],
        "elite4": ["Aaron", "Bertha", "Flint", "Lucian"],
        "champion": ["Cynthia"],
        "bosses": ["Cyrus", "Mars", "Jupiter", "Saturn"],
    },
    "platinum": {
        "id": "platinum",
        "name": "Pokémon Platinum",
        "gen": 4,
        "region": "sinnoh",
        "starters": ["Turtwig", "Chimchar", "Piplup"],
        "walkthrough_slug": "Platinum_walkthrough",
        "shared_with": None,
        "pokeapi_version": "platinum",
        "pokeapi_region": "sinnoh",
        "gym_leaders": ["Roark", "Gardenia", "Maylene", "Crasher Wake", "Fantina", "Byron", "Candice", "Volkner"],
        "rivals": ["Barry"],
        "elite4": ["Aaron", "Bertha", "Flint", "Lucian"],
        "champion": ["Cynthia"],
        "bosses": ["Cyrus", "Mars", "Jupiter", "Saturn", "Giratina"],
    },
    "heartgold": {
        "id": "heartgold",
        "name": "Pokémon HeartGold",
        "gen": 4,
        "region": "johto",
        "starters": ["Chikorita", "Cyndaquil", "Totodile"],
        "walkthrough_slug": "HeartGold_and_SoulSilver_walkthrough",
        "shared_with": "soulsilver",
        "pokeapi_version": "heartgold",
        "pokeapi_region": "johto",
        "gym_leaders": [
            "Falkner", "Bugsy", "Whitney", "Morty", "Chuck", "Jasmine", "Pryce", "Clair",
            "Brock", "Misty", "Lt. Surge", "Erika", "Janine", "Sabrina", "Blaine", "Blue",
        ],
        "rivals": ["Silver"],
        "elite4": ["Will", "Koga", "Bruno", "Karen"],
        "champion": ["Lance"],
        "bosses": ["Giovanni", "Archer", "Ariana", "Petrel", "Proton", "Red"],
    },
    "soulsilver": {
        "id": "soulsilver",
        "name": "Pokémon SoulSilver",
        "gen": 4,
        "region": "johto",
        "starters": ["Chikorita", "Cyndaquil", "Totodile"],
        "walkthrough_slug": "HeartGold_and_SoulSilver_walkthrough",
        "shared_with": "heartgold",
        "pokeapi_version": "soulsilver",
        "pokeapi_region": "johto",
        "gym_leaders": [
            "Falkner", "Bugsy", "Whitney", "Morty", "Chuck", "Jasmine", "Pryce", "Clair",
            "Brock", "Misty", "Lt. Surge", "Erika", "Janine", "Sabrina", "Blaine", "Blue",
        ],
        "rivals": ["Silver"],
        "elite4": ["Will", "Koga", "Bruno", "Karen"],
        "champion": ["Lance"],
        "bosses": ["Giovanni", "Archer", "Ariana", "Petrel", "Proton", "Red"],
    },

    # ── Gen 5 ──────────────────────────────────────────────────────────────────
    "black": {
        "id": "black",
        "name": "Pokémon Black",
        "gen": 5,
        "region": "unova",
        "starters": ["Snivy", "Tepig", "Oshawott"],
        "walkthrough_slug": "Black_and_White_walkthrough",
        "shared_with": "white",
        "pokeapi_version": "black",
        "pokeapi_region": "unova",
        "gym_leaders": ["Cilan", "Chili", "Cress", "Lenora", "Burgh", "Elesa", "Clay", "Skyla", "Brycen", "Drayden", "Iris"],
        "rivals": ["Cheren", "Bianca", "N"],
        "elite4": ["Shauntal", "Marshal", "Grimsley", "Caitlin"],
        "champion": ["Alder"],
        "bosses": ["N", "Ghetsis"],
    },
    "white": {
        "id": "white",
        "name": "Pokémon White",
        "gen": 5,
        "region": "unova",
        "starters": ["Snivy", "Tepig", "Oshawott"],
        "walkthrough_slug": "Black_and_White_walkthrough",
        "shared_with": "black",
        "pokeapi_version": "white",
        "pokeapi_region": "unova",
        "gym_leaders": ["Cilan", "Chili", "Cress", "Lenora", "Burgh", "Elesa", "Clay", "Skyla", "Brycen", "Drayden", "Iris"],
        "rivals": ["Cheren", "Bianca", "N"],
        "elite4": ["Shauntal", "Marshal", "Grimsley", "Caitlin"],
        "champion": ["Alder"],
        "bosses": ["N", "Ghetsis"],
    },
    "black2": {
        "id": "black2",
        "name": "Pokémon Black 2",
        "gen": 5,
        "region": "unova",
        "starters": ["Snivy", "Tepig", "Oshawott"],
        "walkthrough_slug": "Black_2_and_White_2_walkthrough",
        "shared_with": "white2",
        "pokeapi_version": "black-2",
        "pokeapi_region": "unova",
        "gym_leaders": ["Cheren", "Roxie", "Burgh", "Elesa", "Clay", "Skyla", "Drayden", "Marlon"],
        "rivals": ["Hugh"],
        "elite4": ["Shauntal", "Marshal", "Grimsley", "Caitlin"],
        "champion": ["Iris"],
        "bosses": ["Ghetsis", "Colress", "Zinzolin"],
    },
    "white2": {
        "id": "white2",
        "name": "Pokémon White 2",
        "gen": 5,
        "region": "unova",
        "starters": ["Snivy", "Tepig", "Oshawott"],
        "walkthrough_slug": "Black_2_and_White_2_walkthrough",
        "shared_with": "black2",
        "pokeapi_version": "white-2",
        "pokeapi_region": "unova",
        "gym_leaders": ["Cheren", "Roxie", "Burgh", "Elesa", "Clay", "Skyla", "Drayden", "Marlon"],
        "rivals": ["Hugh"],
        "elite4": ["Shauntal", "Marshal", "Grimsley", "Caitlin"],
        "champion": ["Iris"],
        "bosses": ["Ghetsis", "Colress", "Zinzolin"],
    },
}

# All 18 game IDs in release order
ALL_GAME_IDS = [
    "red", "blue", "yellow",
    "gold", "silver", "crystal",
    "ruby", "sapphire", "emerald", "firered", "leafgreen",
    "diamond", "pearl", "platinum", "heartgold", "soulsilver",
    "black", "white", "black2", "white2",
]

# Bulbapedia base URL
BULBAPEDIA_BASE = "https://bulbapedia.bulbagarden.net"
POKEAPI_BASE = "https://pokeapi.co/api/v2"

# Heading keywords that indicate encounter types (for access_notes detection)
ROD_KEYWORDS = {
    "old_rod": ["old rod", "received old rod", "got old rod"],
    "good_rod": ["good rod", "received good rod", "got good rod"],
    "super_rod": ["super rod", "received super rod", "got super rod"],
}

HM_KEYWORDS = {
    "surf": ["hm surf", "hm03", "surf"],
    "cut": ["hm cut", "hm01", "cut"],
    "fly": ["hm fly", "hm02", "fly"],
    "strength": ["hm strength", "hm04", "strength"],
    "flash": ["hm flash", "hm05"],
    "rock_smash": ["hm rock smash", "hm06", "rock smash"],
    "waterfall": ["hm waterfall", "hm07", "waterfall"],
    "whirlpool": ["hm whirlpool", "whirlpool"],
    "rock_climb": ["hm rock climb", "rock climb"],
    "defog": ["hm defog", "defog"],
}

# Words in headings that indicate a location (not a checkpoint or sub-content)
LOCATION_KEYWORDS = [
    "route", "cave", "forest", "lake", "mountain", "island", "city", "town",
    "road", "tunnel", "tower", "ruins", "mansion", "laboratory", "mine", "path",
    "valley", "desert", "park", "safari", "sea", "ocean", "river", "shore",
    "harbor", "port", "ranch", "garden", "meadow", "plateau", "peak", "summit",
    "falls", "bridge", "strait", "bay", "cape", "cove", "grove", "thicket",
    "depths", "castle", "academy", "gym",  # 'gym' can be location when used as heading before the fight
]

# Words in headings that indicate a checkpoint
CHECKPOINT_KEYWORDS = [
    "elite four", "champion", "victory road",  # 'victory road' is sometimes used as checkpoint
]
